Models/Artiekel.cs
using System.ComponentModel.DataAnnotations;

public class Artiekel{
    //Weet niet hoe ik een error message kan krijgen wanneer het id niet uniek is via data annotations
    [Key]
    [Range(1,13,ErrorMessage="Rating must between 1 to 10")] 
    [Required]
    public int Id{get;set;}

    [Required]
    [MaxLength(50)]
    public string Naam{get;set;}

    [Required]
    [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
    public int Potmaat{get;set;}

    [Required]
    public int Planthoogte{get;set;}

    public string? Kleur{get;set;}
    
    [Required]
    public string Productgroep{get;set;}
}

Models/ErrorViewModel.cs
using System;

namespace jimid.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ArtiekelAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace jimid.Controllers
{
    public class ArtiekelAController : Controller
    {
        private readonly MyContext _context;

        public ArtiekelAController(MyContext context)
        {
            _context = context;
        }

        public IQueryable<Artiekel> Sorteer(IQueryable<Artiekel> lijst, string Sorteer){
            if (Sorteer == "naam_oplopend")
                return lijst.OrderBy(s=>s.Naam.ToLower());
            else if(Sorteer == "naam_aflopend"){
                return  lijst.OrderByDescending(s=>s.Naam.ToLower());
            }
            else if(Sorteer =="potmaat_oplopend"){
                return lijst.OrderBy(s=>s.Potmaat);
            }
            
            else if(Sorteer == "potmaat_aflopend"){
                return lijst.OrderByDescending(s=>s.Potmaat);
            }
            else if(Sorteer =="kleur_oplopend"){
                return lijst.OrderBy(s=>s.Kleur.ToLower());
            }
            
            else if(Sorteer == "kleur_aflopend"){
                return lijst.OrderByDescending(s=>s.Kleur.ToLower());
            }
            else if(Sorteer =="productgroep_oplopend"){
                return lijst.OrderBy(s=>s.Productgroep.ToLower());
            }
            
            else if(Sorteer == "productgroep_aflopend"){
                return lijst.OrderByDescending(s=>s.Productgroep.ToLower());
            }
            else{
                return lijst.OrderBy(s=>s.Naam.ToLower());
            }
        }
        

        public IQueryable<Artiekel> Pagineer(IQueryable<Artiekel> lijst, int pagina,int aantal){
            if (pagina <0)
                pagina= 0;
            return lijst.Skip((pagina)*aantal).Take(aantal);
        }

        // GET: Artiekel
        public async Task<IActionResult> Index(string sorteer, string zoek, int pagina)
        {
            if(sorteer==null) 
                sorteer= "naam_oplopend";
            ViewData["sorteer"] = sorteer;
            ViewData["pagina"] = pagina;
            ViewData["heeftVolgende"] = (pagina+1) * 10 < _context.Artiekel.Count();
            ViewData["heeftVorige"] = pagina>0;
            return View(await Pagineer(Sorteer(_context.Artiekel,sorteer), pagina, 10).ToListAsync());
        }

        private bool ArtiekelExists(int id)
        {
            return _context.Artiekel.Any(e => e.Id == id);
        }
    }
}

Controllers/ArtiekelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace jimid.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ArtiekelController : ControllerBase
    {
        private readonly MyContext _context;

        public ArtiekelController(MyContext context)
        {
            _context = context;
        }

        // GET: api/Artiekel
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Artiekel>>> GetArtiekel()
        {
            return await _context.Artiekel.ToListAsync();
        }

        // GET: api/Artiekel/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Artiekel>> GetArtiekel(int id)
        {
            var artiekel = await _context.Artiekel.FindAsync(id);

            if (artiekel == null)
            {
                return NotFound();
            }

            return artiekel;
        }

        // PUT: api/Artiekel/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutArtiekel(int id, Artiekel artiekel)
        {
            if (id != artiekel.Id)
            {
                return BadRequest();
            }

            _context.Entry(artiekel).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ArtiekelExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Artiekel
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Artiekel>> PostArtiekel(Artiekel artiekel)
        {
            _context.Artiekel.Add(artiekel);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetArtiekel", new { id = artiekel.Id }, artiekel);
        }

        // DELETE: api/Artiekel/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteArtiekel(int id)
        {
            var artiekel = await _context.Artiekel.FindAsync(id);
            if (artiekel == null)
            {
                return NotFound();
            }

            _context.Artiekel.Remove(artiekel);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool ArtiekelExists(int id)
        {
            return _context.Artiekel.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using jimid.Models;

namespace jimid.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/ArtiekelA/Index.cshtml
@model IEnumerable<Artiekel>

@{
    ViewData["Title"] = "Index";
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="naam_oplopend">↑</a>
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="naam_aflopend">↓</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Potmaat)
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="potmaat_oplopend">↑</a>
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="potmaat_aflopend">↓</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Planthoogte)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kleur)
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="kleur_oplopend">↑</a>
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="kleur_aflopend">↓</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Productgroep)
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="productgroep_oplopend">↑</a>
                <a asp-controller="ArtiekelA" asp-action="Index" asp-route-sorteer="productgroep_aflopend">↓</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Potmaat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Planthoogte)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kleur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Productgroep)
            </td>
        </tr>
}
    </tbody>
</table>
@if((bool)ViewData["heeftVolgende"] ){
        <a asp-controller="ArtiekelA" asp-action="Index" asp-route-pagina='@((int)ViewData["pagina"]+1)'>Volgende</a>
}@if((bool)ViewData["heeftVorige"] ){
        <a asp-controller="ArtiekelA" asp-action="Index" asp-route-pagina='@((int)ViewData["pagina"]-1)'>Vorige</a>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - jimid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">jimid</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - jimid - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>